logging:
  level:
    com.daimler.dmd: DEBUG
    #org.hibernate.type: TRACE
    #org.hibernate.SQL: DEBUG

spring:
  application:
    name: note-service

  datasource:
    url: jdbc:postgresql://localhost:5439/notedb
    username: note-user
    password: Welcome123

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: xxxxxxxxxx
            client-secret: xxxxxxxxxxxxxxx
            scope:
              - profile
              - email
          github:
            client-id: xxxxxxxxxxx
            client-secret: xxxxxxxxxxxxxxxxxx
            scope:
              - read:user
              - user:email

  mail:
    host: smtp.gmail.com
    port: 587
    username: siyathedev@gmail.com
    password: xxxxxxxxxxxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  token:
    secret: xxxxxxxxxxxxxxx
    expirationMs: 864000000
  front-end:
    url: http://localhost:3000
